### ISSUE TITLE
Raising JIRA's

### ISSUE THREAD

**Issue by robhuzzey** [holidayextras/culture#35]
I was wondering if we should have a document around raising JIRA's. What is required? How to label correctly etc?

Wanted to know thoughts around this.

**Comment by SkylerAvery** [comment]
Some pods use a template for certain types of JIRAs and I suggested adding in a template when a JIRA is ready for testing(see https://github.com/holidayextras/hx-culture/pull/22). As long as the required information needed to complete the JIRA is in the description then a template could vary from pod to pod.

**Comment by lukehansell** [comment]
I'd be interested to see the different templates that pods have. Any chance people could paste them here?

**Comment by hxtonihurcombe** [comment]
Hey @lukehansell-hx the insurance pod now make sure we have the following in the description before a ticket is pulled into the sprint:

Requirements
Reason/ Goal
Automated Testing
Testing
Insight

**Comment by hpoom** [comment]
I would not add a doc here on raising JIRA's. Sorry @robhuzzey. My reasons are as follows.
- Culture repo is open and this is useless info to anybody outside HX
- Jira templates will change the doc would become out of date
- There is not one way to raise a Jira, I currently know of at least 3 different Jira setups but there are probably more. Many PODs use a different template at the moment
- Shortbreaks and UK Airports use Jira very differently, I expect DE Airports do too. Culture is a group repo, for stuff that is the same across the group not a POD level thing.

**Comment by robhuzzey** [comment]
Thanks all... I will be closing this. @hpoom point about this being a public repo I had forgot about that... JIRA is a very specific thing for our business.
