### ISSUE TITLE
Should we integrate guilds into our culture repo?

### ISSUE THREAD

**Issue by connormeredith** [holidayextras/culture#78]
Now that we've implemented guilds across the web team should we have a folder in the culture repo dedicated to guild related documentation? For example, each guild could have it's own markdown document where their current aims and achievements could be listed. We could even have a separate repo. I just want to get some ideas to help give transparency to each guild and allow everyone to get an overview on each guild's focus and progress. Any thoughts?

**Comment by hx-markterry** [comment]
i dont think that our public culture repo is the right place for _all_ of this.

Any achievements by a guild would probably be documented separately on this repos in the format of guides, best practices and tech choices.

If achievements are worth sharing it should be done in a face to face session with the rest of the group, on an ad hoc or at some scheduled guide demo time.

An overall guide info doc would be useful to new starters etc.

I'd hope that the guild meetings will use some kind of working group style google doc that is shared with the rest of the business, this will give low level info to others.

We may have to revisit this discussion until we have had one or two guild meetings.

**Comment by pmcnr-hx** [comment]
We'll have weekly summaries for the guilds' activities. I would favour to write these in Markdown and store in a git repository. Although we're very open, I am not sure if there'll ever be any sensitive content that should remain private.

**Comment by hx-markterry** [comment]
To re-interate on my last comment i think that guild info should be in our culture repo as it is/will be part of our web team culture, the low level detail can be put somewhere else in my opinion (maybe the recently created other repo).

This whole doc:

https://github.com/holidayextras/guilds/blob/master/README.md

Should be moved into this repo.
